apiVersion: v1
kind: Service
metadata:
  name: servicio-notificaciones
spec:
  type: NodePort
  selector:
    app: servicio-notificaciones #enruta a los pods con esta etiqueta
  ports:
    - port: 8080
      targetPort: 8080
