# La solicitud de conexión a la base viene
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/arka}
spring.datasource.username=${DB_USER:arka}
spring.datasource.password=${DB_PASSWORD:arka}

# Hibernate valida
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Ejecuta schema.sql y data.sql al iniciar la aplicación
spring.sql.init.mode=always

spring.application.name=servicio-solicitudes
notificaciones.url=${NOTIFICACIONES_URL:http://localhost:8081/eventos/solicitud-enviada}
